
export const flowerCategoryType = [
  "Alstromerias",
  "Calla Lillies",
  "Carnations",
  "Disbud Chrysanthemums",
  "Ecuador Roses",
  "Follage",
  "Gerbras",
  "Malaysian Chrysanthemums",
  "Spray Carnations",
  "Spray Chrysanthemums",
  "Super Premiums",
  "Uncategorized",
  "Intermediate Roses",
  "Premium Roses",
  "Sprays",
  "Wholesale Mixes"
];
export const flowerSize = ['s', 'm', 'l', 'xl', 'xxl'];
export const flowerFragrance = [
  'rose',
  'neroli',
  'jasmine',
  'geranium',
  'lavender',
  'ylang-ylang',
  'lily of the valley',
  'violet and peony',
];


export const flowers = [
  {
    "seller": "65b288597bc3450ab4cea394",
    "name": "Sunflower Bouquet",
    "price": 19.99,
    "quantity": 15,
    "image": "https://images.fineartamerica.com/images-medium-large-5/looking-for-you-priska-wettstein.jpg",
    "bloomDate": "Summer",
    "color": "Yellow",
    "type": "Sprays",
    "size": "l",
    "arrangement": "Bouquet",
    "style": "Modern",
    "fragrance": "lily of the valley"
  },
  {
    "seller": "65b288597bc3450ab4cea394",
    "name": "Ecuador Rose Deluxe",
    "price": 29.99,
    "quantity": 10,
    "image": "https://render.fineartamerica.com/images/rendered/square-dynamic/small/images-medium-large-5/mums-in-a-cup-priska-wettstein.jpg",
    "bloomDate": "Spring",
    "color": "Red",
    "type": "Ecuador Roses",
    "size": "xl",
    "arrangement": "Boxed",
    "style": "Classic",
    "fragrance": "rose"
  },
  {
    "seller": "65b288597bc3450ab4cea394",
    "name": "Lavender Bliss",
    "price": 14.99,
    "quantity": 20,
    "image": "https://images.fineartamerica.com/images-medium-large-5/rachel-dahlia-flower-square-barbara-griffin.jpg",
    "bloomDate": "Spring",
    "color": "Purple",
    "type": "Sprays",
    "size": "m",
    "arrangement": "Bouquet",
    "style": "Modern",
    "fragrance": "lavender"
  },
  {
    "seller": "65b288597bc3450ab4cea394",
    "name": "Chrysanthemum Medley",
    "price": 22.99,
    "quantity": 12,
    "image": "https://images.fineartamerica.com/images-medium-large-5/looking-for-you-priska-wettstein.jpg",
    "bloomDate": "Autumn",
    "color": "Multi-colored",
    "type": "Spray Chrysanthemums",
    "size": "l",
    "arrangement": "Mixed",
    "style": "Eclectic",
    "fragrance": "geranium"
  },
  {
    "seller": "65b288597bc3450ab4cea394",
    "name": "Rose Radiance",
    "price": 18.99,
    "quantity": 18,
    "image": "https://render.fineartamerica.com/images/rendered/square-dynamic/small/images-medium-large-5/mums-in-a-cup-priska-wettstein.jpg",
    "bloomDate": "Spring",
    "color": "Pink",
    "type": "Premium Roses",
    "size": "m",
    "arrangement": "Bouquet",
    "style": "Romantic",
    "fragrance": "rose"
  },
  {
    "seller": "65b288597bc3450ab4cea394",
    "name": "Midsummer Dream",
    "price": 26.99,
    "quantity": 8,
    "image": "https://images.fineartamerica.com/images-medium-large-5/rachel-dahlia-flower-square-barbara-griffin.jpg",
    "bloomDate": "Summer",
    "color": "White",
    "type": "Calla Lillies",
    "size": "xl",
    "arrangement": "Elongated",
    "style": "Elegant",
    "fragrance": "jasmine"
  },
  {
    "seller": "65b288597bc3450ab4cea394",
    "name": "Azure Elegance",
    "price": 32.99,
    "quantity": 14,
    "image": "https://images.fineartamerica.com/images-medium-large-5/looking-for-you-priska-wettstein.jpg",
    "bloomDate": "Spring",
    "color": "Blue",
    "type": "Alstromerias",
    "size": "l",
    "arrangement": "Vase",
    "style": "Contemporary",
    "fragrance": "lily of the valley"
  },
  {
    "seller": "65b288597bc3450ab4cea394",
    "name": "Golden Harvest",
    "price": 21.99,
    "quantity": 16,
    "image": "https://render.fineartamerica.com/images/rendered/square-dynamic/small/images-medium-large-5/mums-in-a-cup-priska-wettstein.jpg",
    "bloomDate": "Autumn",
    "color": "Yellow",
    "type": "Gerbras",
    "size": "m",
    "arrangement": "Basket",
    "style": "Rustic",
    "fragrance": "geranium"
  },
  {
    "seller": "65b288597bc3450ab4cea394",
    "name": "Mystic Orchids",
    "price": 28.99,
    "quantity": 10,
    "image": "https://images.fineartamerica.com/images-medium-large-5/rachel-dahlia-flower-square-barbara-griffin.jpg",
    "bloomDate": "Winter",
    "color": "Purple",
    "type": "Uncategorized",
    "size": "l",
    "arrangement": "Cascading",
    "style": "Exotic",
    "fragrance": "ylang-ylang"
  },
  {
    "seller": "65b288597bc3450ab4cea394",
    "name": "Autumn Radiance",
    "price": 19.99,
    "quantity": 22,
    "image": "https://images.fineartamerica.com/images-medium-large-5/looking-for-you-priska-wettstein.jpg",
    "bloomDate": "Autumn",
    "color": "Orange",
    "type": "Sprays",
    "size": "s",
    "arrangement": "Bouquet",
    "style": "Vibrant",
    "fragrance": "jasmine"
  },
  {
    "seller": "65b288597bc3450ab4cea394",
    "name": "Silken Petal Mix",
    "price": 23.99,
    "quantity": 15,
    "image": "https://render.fineartamerica.com/images/rendered/square-dynamic/small/images-medium-large-5/mums-in-a-cup-priska-wettstein.jpg",
    "bloomDate": "Spring",
    "color": "Mixed",
    "type": "Wholesale Mixes",
    "size": "xl",
    "arrangement": "Mixed",
    "style": "Eclectic",
    "fragrance": "violet and peony"
  },
  {
    "seller": "65b288597bc3450ab4cea394",
    "name": "Winter Wonderland",
    "price": 25.99,
    "quantity": 12,
    "image": "https://images.fineartamerica.com/images-medium-large-5/rachel-dahlia-flower-square-barbara-griffin.jpg",
    "bloomDate": "Winter",
    "color": "White",
    "type": "Premium Roses",
    "size": "l",
    "arrangement": "Bouquet",
    "style": "Classic",
    "fragrance": "lily of the valley"
  }
]